package com.shev.compilation.user.dao.mapper;

import com.shev.compilation.user.entity.DutyPermissionRelationDelete;

import java.util.List;

public interface DutyPermissionRelationDeleteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty_permission_relation_delete
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty_permission_relation_delete
     *
     * @mbg.generated
     */
    int insert(DutyPermissionRelationDelete record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty_permission_relation_delete
     *
     * @mbg.generated
     */
    DutyPermissionRelationDelete selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty_permission_relation_delete
     *
     * @mbg.generated
     */
    List<DutyPermissionRelationDelete> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty_permission_relation_delete
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DutyPermissionRelationDelete record);
}