package com.shev.compilation.user.dao.mapper;

import com.shev.compilation.user.entity.Duty;

import java.util.List;

public interface DutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    int insert(Duty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    Duty selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    List<Duty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Duty record);
}