package com.shev.compilation.user.dao.mapper;

import com.shev.compilation.user.entity.PermissionDelete;

import java.util.List;

public interface PermissionDeleteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_delete
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_delete
     *
     * @mbg.generated
     */
    int insert(PermissionDelete record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_delete
     *
     * @mbg.generated
     */
    PermissionDelete selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_delete
     *
     * @mbg.generated
     */
    List<PermissionDelete> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_delete
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PermissionDelete record);
}