package com.shev.compilation.user.dao.mapper;

import com.shev.compilation.user.entity.UserRecordDelete;

import java.util.List;

public interface UserRecordDeleteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record_delete
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record_delete
     *
     * @mbg.generated
     */
    int insert(UserRecordDelete record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record_delete
     *
     * @mbg.generated
     */
    UserRecordDelete selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record_delete
     *
     * @mbg.generated
     */
    List<UserRecordDelete> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_record_delete
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRecordDelete record);
}