package com.shev.compilation.user.dao.mapper;

import com.shev.compilation.user.entity.UserPreference;
import java.util.List;

public interface UserPreferenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_preference
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_preference
     *
     * @mbg.generated
     */
    int insert(UserPreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_preference
     *
     * @mbg.generated
     */
    UserPreference selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_preference
     *
     * @mbg.generated
     */
    List<UserPreference> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_preference
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserPreference record);
}