package com.shev.compilation.user.dao.mapper;

import com.shev.compilation.user.entity.UserDutyRelation;
import java.util.List;

public interface UserDutyRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty_relation
     *
     * @mbg.generated
     */
    int insert(UserDutyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty_relation
     *
     * @mbg.generated
     */
    UserDutyRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty_relation
     *
     * @mbg.generated
     */
    List<UserDutyRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDutyRelation record);
}