package com.shev.compilation.user.dao.mapper;

import com.shev.compilation.user.entity.UserPermissionRelationDelete;

import java.util.List;

public interface UserPermissionRelationDeleteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission_relation_delete
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission_relation_delete
     *
     * @mbg.generated
     */
    int insert(UserPermissionRelationDelete record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission_relation_delete
     *
     * @mbg.generated
     */
    UserPermissionRelationDelete selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission_relation_delete
     *
     * @mbg.generated
     */
    List<UserPermissionRelationDelete> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission_relation_delete
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserPermissionRelationDelete record);
}