package com.shev.compilation.user.dao.mapper;

import com.shev.compilation.user.entity.UserPermissionRelation;
import java.util.List;

public interface UserPermissionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission_relation
     *
     * @mbg.generated
     */
    int insert(UserPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission_relation
     *
     * @mbg.generated
     */
    UserPermissionRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission_relation
     *
     * @mbg.generated
     */
    List<UserPermissionRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserPermissionRelation record);
}