package com.shev.itembank.system.entity;

import java.io.Serializable;
import java.util.Date;

public class Partner implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.TENANT_ID
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.API_ENDPOINT
     *
     * @mbg.generated
     */
    private String apiEndpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.ACCESS_KEY
     *
     * @mbg.generated
     */
    private String accessKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.SECRET_KEY
     *
     * @mbg.generated
     */
    private String secretKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.ENABLED
     *
     * @mbg.generated
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.LONG_TICKET
     *
     * @mbg.generated
     */
    private String longTicket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.TICKET_DATE_THRU
     *
     * @mbg.generated
     */
    private Date ticketDateThru;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.REFRESH_TOKEN
     *
     * @mbg.generated
     */
    private String refreshToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.COMMENT
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.DATE_FROM
     *
     * @mbg.generated
     */
    private Date dateFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.DATE_THRU
     *
     * @mbg.generated
     */
    private Date dateThru;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.ID
     *
     * @return the value of partner.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.ID
     *
     * @param id the value for partner.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.TENANT_ID
     *
     * @return the value of partner.TENANT_ID
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.TENANT_ID
     *
     * @param tenantId the value for partner.TENANT_ID
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.TYPE
     *
     * @return the value of partner.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.TYPE
     *
     * @param type the value for partner.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.NAME
     *
     * @return the value of partner.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.NAME
     *
     * @param name the value for partner.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.API_ENDPOINT
     *
     * @return the value of partner.API_ENDPOINT
     *
     * @mbg.generated
     */
    public String getApiEndpoint() {
        return apiEndpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.API_ENDPOINT
     *
     * @param apiEndpoint the value for partner.API_ENDPOINT
     *
     * @mbg.generated
     */
    public void setApiEndpoint(String apiEndpoint) {
        this.apiEndpoint = apiEndpoint == null ? null : apiEndpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.ACCESS_KEY
     *
     * @return the value of partner.ACCESS_KEY
     *
     * @mbg.generated
     */
    public String getAccessKey() {
        return accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.ACCESS_KEY
     *
     * @param accessKey the value for partner.ACCESS_KEY
     *
     * @mbg.generated
     */
    public void setAccessKey(String accessKey) {
        this.accessKey = accessKey == null ? null : accessKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.SECRET_KEY
     *
     * @return the value of partner.SECRET_KEY
     *
     * @mbg.generated
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.SECRET_KEY
     *
     * @param secretKey the value for partner.SECRET_KEY
     *
     * @mbg.generated
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey == null ? null : secretKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.ENABLED
     *
     * @return the value of partner.ENABLED
     *
     * @mbg.generated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.ENABLED
     *
     * @param enabled the value for partner.ENABLED
     *
     * @mbg.generated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.LONG_TICKET
     *
     * @return the value of partner.LONG_TICKET
     *
     * @mbg.generated
     */
    public String getLongTicket() {
        return longTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.LONG_TICKET
     *
     * @param longTicket the value for partner.LONG_TICKET
     *
     * @mbg.generated
     */
    public void setLongTicket(String longTicket) {
        this.longTicket = longTicket == null ? null : longTicket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.TICKET_DATE_THRU
     *
     * @return the value of partner.TICKET_DATE_THRU
     *
     * @mbg.generated
     */
    public Date getTicketDateThru() {
        return ticketDateThru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.TICKET_DATE_THRU
     *
     * @param ticketDateThru the value for partner.TICKET_DATE_THRU
     *
     * @mbg.generated
     */
    public void setTicketDateThru(Date ticketDateThru) {
        this.ticketDateThru = ticketDateThru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.REFRESH_TOKEN
     *
     * @return the value of partner.REFRESH_TOKEN
     *
     * @mbg.generated
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.REFRESH_TOKEN
     *
     * @param refreshToken the value for partner.REFRESH_TOKEN
     *
     * @mbg.generated
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.COMMENT
     *
     * @return the value of partner.COMMENT
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.COMMENT
     *
     * @param comment the value for partner.COMMENT
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.DATE_FROM
     *
     * @return the value of partner.DATE_FROM
     *
     * @mbg.generated
     */
    public Date getDateFrom() {
        return dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.DATE_FROM
     *
     * @param dateFrom the value for partner.DATE_FROM
     *
     * @mbg.generated
     */
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.DATE_THRU
     *
     * @return the value of partner.DATE_THRU
     *
     * @mbg.generated
     */
    public Date getDateThru() {
        return dateThru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.DATE_THRU
     *
     * @param dateThru the value for partner.DATE_THRU
     *
     * @mbg.generated
     */
    public void setDateThru(Date dateThru) {
        this.dateThru = dateThru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.CREATE_TIME
     *
     * @return the value of partner.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.CREATE_TIME
     *
     * @param createTime the value for partner.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner.UPDATE_TIME
     *
     * @return the value of partner.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner.UPDATE_TIME
     *
     * @param updateTime the value for partner.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", type=").append(type);
        sb.append(", name=").append(name);
        sb.append(", apiEndpoint=").append(apiEndpoint);
        sb.append(", accessKey=").append(accessKey);
        sb.append(", secretKey=").append(secretKey);
        sb.append(", enabled=").append(enabled);
        sb.append(", longTicket=").append(longTicket);
        sb.append(", ticketDateThru=").append(ticketDateThru);
        sb.append(", refreshToken=").append(refreshToken);
        sb.append(", comment=").append(comment);
        sb.append(", dateFrom=").append(dateFrom);
        sb.append(", dateThru=").append(dateThru);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}