package com.shev.itembank.exercise.mapper;

import com.shev.itembank.exercise.entity.Exercise;
import java.util.List;

public interface ExerciseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    int insert(Exercise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    Exercise selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    List<Exercise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Exercise record);
}