spring:
  application:
    name: item-bank-system-service
  profiles:
    active: dev
  datasource:
    data-username: root
    data-password: root
    url: jdbc:mysql://192.168.99.53:44001/paper?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
