package com.shev.itembank.resource.entity;

import java.io.Serializable;
import java.util.Date;

public class Media implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.TENANT_ID
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.DEPARTMENT_ID
     *
     * @mbg.generated
     */
    private String departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.RESOURCE_ID
     *
     * @mbg.generated
     */
    private String resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.NARROW_RESOURCE_ID
     *
     * @mbg.generated
     */
    private String narrowResourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.ENLARGE_RESOURCE_ID
     *
     * @mbg.generated
     */
    private String enlargeResourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table media
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.ID
     *
     * @return the value of media.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.ID
     *
     * @param id the value for media.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.TENANT_ID
     *
     * @return the value of media.TENANT_ID
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.TENANT_ID
     *
     * @param tenantId the value for media.TENANT_ID
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.DEPARTMENT_ID
     *
     * @return the value of media.DEPARTMENT_ID
     *
     * @mbg.generated
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.DEPARTMENT_ID
     *
     * @param departmentId the value for media.DEPARTMENT_ID
     *
     * @mbg.generated
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.RESOURCE_ID
     *
     * @return the value of media.RESOURCE_ID
     *
     * @mbg.generated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.RESOURCE_ID
     *
     * @param resourceId the value for media.RESOURCE_ID
     *
     * @mbg.generated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.TITLE
     *
     * @return the value of media.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.TITLE
     *
     * @param title the value for media.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.NARROW_RESOURCE_ID
     *
     * @return the value of media.NARROW_RESOURCE_ID
     *
     * @mbg.generated
     */
    public String getNarrowResourceId() {
        return narrowResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.NARROW_RESOURCE_ID
     *
     * @param narrowResourceId the value for media.NARROW_RESOURCE_ID
     *
     * @mbg.generated
     */
    public void setNarrowResourceId(String narrowResourceId) {
        this.narrowResourceId = narrowResourceId == null ? null : narrowResourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.ENLARGE_RESOURCE_ID
     *
     * @return the value of media.ENLARGE_RESOURCE_ID
     *
     * @mbg.generated
     */
    public String getEnlargeResourceId() {
        return enlargeResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.ENLARGE_RESOURCE_ID
     *
     * @param enlargeResourceId the value for media.ENLARGE_RESOURCE_ID
     *
     * @mbg.generated
     */
    public void setEnlargeResourceId(String enlargeResourceId) {
        this.enlargeResourceId = enlargeResourceId == null ? null : enlargeResourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.CREATE_TIME
     *
     * @return the value of media.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.CREATE_TIME
     *
     * @param createTime the value for media.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.UPDATE_TIME
     *
     * @return the value of media.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.UPDATE_TIME
     *
     * @param updateTime the value for media.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", departmentId=").append(departmentId);
        sb.append(", resourceId=").append(resourceId);
        sb.append(", title=").append(title);
        sb.append(", narrowResourceId=").append(narrowResourceId);
        sb.append(", enlargeResourceId=").append(enlargeResourceId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}