spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    account:
      master:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=true
        data-username: root
        data-password:
      slave:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/zmstd?useUnicode=true&characterEncoding=utf-8&useSSL=true
        data-username: root
        data-password:
    edumeta:
      master1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.129:50121/edumeta?useUnicode=true&characterEncoding=utf-8&useSSL=true
        data-username: root
        data-password: root
      master2:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.129:50122/edumeta?useUnicode=true&characterEncoding=utf-8&useSSL=true
        data-username: root
        data-password: root
      master3:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.129:50123/edumeta?useUnicode=true&characterEncoding=utf-8&useSSL=true
        data-username: root
        data-password: root
      master4:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.129:50124/edumeta?useUnicode=true&characterEncoding=utf-8&useSSL=true
        data-username: root
        data-password: root
      cluster1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.129:50131/edumeta?useUnicode=true&characterEncoding=utf-8&useSSL=true
        data-username: root
        data-password: root
      cluster2:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.129:50132/edumeta?useUnicode=true&characterEncoding=utf-8&useSSL=true
        data-username: root
        data-password: root
      cluster3:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.129:50133/edumeta?useUnicode=true&characterEncoding=utf-8&useSSL=true
        data-username: root
        data-password: root
      cluster4:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.129:50134/edumeta?useUnicode=true&characterEncoding=utf-8&useSSL=true
        data-username: root
        data-password: root
