package com.shev.compilation.user.entity;

import java.io.Serializable;
import java.util.Date;

public class UserPreference implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_preference.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_preference.RETAIN_SUBJECT_STAGE
     *
     * @mbg.generated
     */
    private Boolean retainSubjectStage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_preference.RETAIN_EXERCISE_TYPE
     *
     * @mbg.generated
     */
    private Boolean retainExerciseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_preference.RETAIN_CHECK_INFO
     *
     * @mbg.generated
     */
    private Boolean retainCheckInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_preference.AUTO_BACKGROUND_PICTURE
     *
     * @mbg.generated
     */
    private Boolean autoBackgroundPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_preference.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_preference.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_preference.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_preference
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_preference.ID
     *
     * @return the value of user_preference.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_preference.ID
     *
     * @param id the value for user_preference.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_preference.RETAIN_SUBJECT_STAGE
     *
     * @return the value of user_preference.RETAIN_SUBJECT_STAGE
     *
     * @mbg.generated
     */
    public Boolean getRetainSubjectStage() {
        return retainSubjectStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_preference.RETAIN_SUBJECT_STAGE
     *
     * @param retainSubjectStage the value for user_preference.RETAIN_SUBJECT_STAGE
     *
     * @mbg.generated
     */
    public void setRetainSubjectStage(Boolean retainSubjectStage) {
        this.retainSubjectStage = retainSubjectStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_preference.RETAIN_EXERCISE_TYPE
     *
     * @return the value of user_preference.RETAIN_EXERCISE_TYPE
     *
     * @mbg.generated
     */
    public Boolean getRetainExerciseType() {
        return retainExerciseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_preference.RETAIN_EXERCISE_TYPE
     *
     * @param retainExerciseType the value for user_preference.RETAIN_EXERCISE_TYPE
     *
     * @mbg.generated
     */
    public void setRetainExerciseType(Boolean retainExerciseType) {
        this.retainExerciseType = retainExerciseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_preference.RETAIN_CHECK_INFO
     *
     * @return the value of user_preference.RETAIN_CHECK_INFO
     *
     * @mbg.generated
     */
    public Boolean getRetainCheckInfo() {
        return retainCheckInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_preference.RETAIN_CHECK_INFO
     *
     * @param retainCheckInfo the value for user_preference.RETAIN_CHECK_INFO
     *
     * @mbg.generated
     */
    public void setRetainCheckInfo(Boolean retainCheckInfo) {
        this.retainCheckInfo = retainCheckInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_preference.AUTO_BACKGROUND_PICTURE
     *
     * @return the value of user_preference.AUTO_BACKGROUND_PICTURE
     *
     * @mbg.generated
     */
    public Boolean getAutoBackgroundPicture() {
        return autoBackgroundPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_preference.AUTO_BACKGROUND_PICTURE
     *
     * @param autoBackgroundPicture the value for user_preference.AUTO_BACKGROUND_PICTURE
     *
     * @mbg.generated
     */
    public void setAutoBackgroundPicture(Boolean autoBackgroundPicture) {
        this.autoBackgroundPicture = autoBackgroundPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_preference.USER_ID
     *
     * @return the value of user_preference.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_preference.USER_ID
     *
     * @param userId the value for user_preference.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_preference.CREATE_TIME
     *
     * @return the value of user_preference.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_preference.CREATE_TIME
     *
     * @param createTime the value for user_preference.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_preference.UPDATE_TIME
     *
     * @return the value of user_preference.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_preference.UPDATE_TIME
     *
     * @param updateTime the value for user_preference.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_preference
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", retainSubjectStage=").append(retainSubjectStage);
        sb.append(", retainExerciseType=").append(retainExerciseType);
        sb.append(", retainCheckInfo=").append(retainCheckInfo);
        sb.append(", autoBackgroundPicture=").append(autoBackgroundPicture);
        sb.append(", userId=").append(userId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}