package com.shev.compilation.user.entity;

import java.io.Serializable;
import java.util.Date;

public class UserLoginDelete implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_delete.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_delete.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_delete.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_delete.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_delete.COMMENT
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_delete.LONG_TICKET
     *
     * @mbg.generated
     */
    private String longTicket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_delete.DATE_THRU
     *
     * @mbg.generated
     */
    private Date dateThru;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_delete.TENANT_ID
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_delete.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_delete.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_login_delete
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_delete.ID
     *
     * @return the value of user_login_delete.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_delete.ID
     *
     * @param id the value for user_login_delete.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_delete.USER_ID
     *
     * @return the value of user_login_delete.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_delete.USER_ID
     *
     * @param userId the value for user_login_delete.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_delete.USER_NAME
     *
     * @return the value of user_login_delete.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_delete.USER_NAME
     *
     * @param userName the value for user_login_delete.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_delete.PASSWORD
     *
     * @return the value of user_login_delete.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_delete.PASSWORD
     *
     * @param password the value for user_login_delete.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_delete.COMMENT
     *
     * @return the value of user_login_delete.COMMENT
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_delete.COMMENT
     *
     * @param comment the value for user_login_delete.COMMENT
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_delete.LONG_TICKET
     *
     * @return the value of user_login_delete.LONG_TICKET
     *
     * @mbg.generated
     */
    public String getLongTicket() {
        return longTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_delete.LONG_TICKET
     *
     * @param longTicket the value for user_login_delete.LONG_TICKET
     *
     * @mbg.generated
     */
    public void setLongTicket(String longTicket) {
        this.longTicket = longTicket == null ? null : longTicket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_delete.DATE_THRU
     *
     * @return the value of user_login_delete.DATE_THRU
     *
     * @mbg.generated
     */
    public Date getDateThru() {
        return dateThru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_delete.DATE_THRU
     *
     * @param dateThru the value for user_login_delete.DATE_THRU
     *
     * @mbg.generated
     */
    public void setDateThru(Date dateThru) {
        this.dateThru = dateThru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_delete.TENANT_ID
     *
     * @return the value of user_login_delete.TENANT_ID
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_delete.TENANT_ID
     *
     * @param tenantId the value for user_login_delete.TENANT_ID
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_delete.CREATE_TIME
     *
     * @return the value of user_login_delete.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_delete.CREATE_TIME
     *
     * @param createTime the value for user_login_delete.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_delete.UPDATE_TIME
     *
     * @return the value of user_login_delete.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_delete.UPDATE_TIME
     *
     * @param updateTime the value for user_login_delete.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_delete
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", comment=").append(comment);
        sb.append(", longTicket=").append(longTicket);
        sb.append(", dateThru=").append(dateThru);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}