package com.shev.compilation.user.entity;

import java.io.Serializable;
import java.util.Date;

public class UserPermissionRelationDelete implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission_relation_delete.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission_relation_delete.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission_relation_delete.PERMISSION_ID
     *
     * @mbg.generated
     */
    private String permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission_relation_delete.EDUCATIONAL_STAGE_ID
     *
     * @mbg.generated
     */
    private String educationalStageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission_relation_delete.SUBJECT_ID
     *
     * @mbg.generated
     */
    private String subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission_relation_delete.CATEGORY_ID
     *
     * @mbg.generated
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission_relation_delete.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission_relation_delete.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission_relation_delete.CREATE_USER_ID
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permission_relation_delete.UPDATE_USER_ID
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_permission_relation_delete
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission_relation_delete.ID
     *
     * @return the value of user_permission_relation_delete.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission_relation_delete.ID
     *
     * @param id the value for user_permission_relation_delete.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission_relation_delete.USER_ID
     *
     * @return the value of user_permission_relation_delete.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission_relation_delete.USER_ID
     *
     * @param userId the value for user_permission_relation_delete.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission_relation_delete.PERMISSION_ID
     *
     * @return the value of user_permission_relation_delete.PERMISSION_ID
     *
     * @mbg.generated
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission_relation_delete.PERMISSION_ID
     *
     * @param permissionId the value for user_permission_relation_delete.PERMISSION_ID
     *
     * @mbg.generated
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission_relation_delete.EDUCATIONAL_STAGE_ID
     *
     * @return the value of user_permission_relation_delete.EDUCATIONAL_STAGE_ID
     *
     * @mbg.generated
     */
    public String getEducationalStageId() {
        return educationalStageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission_relation_delete.EDUCATIONAL_STAGE_ID
     *
     * @param educationalStageId the value for user_permission_relation_delete.EDUCATIONAL_STAGE_ID
     *
     * @mbg.generated
     */
    public void setEducationalStageId(String educationalStageId) {
        this.educationalStageId = educationalStageId == null ? null : educationalStageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission_relation_delete.SUBJECT_ID
     *
     * @return the value of user_permission_relation_delete.SUBJECT_ID
     *
     * @mbg.generated
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission_relation_delete.SUBJECT_ID
     *
     * @param subjectId the value for user_permission_relation_delete.SUBJECT_ID
     *
     * @mbg.generated
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission_relation_delete.CATEGORY_ID
     *
     * @return the value of user_permission_relation_delete.CATEGORY_ID
     *
     * @mbg.generated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission_relation_delete.CATEGORY_ID
     *
     * @param categoryId the value for user_permission_relation_delete.CATEGORY_ID
     *
     * @mbg.generated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission_relation_delete.CREATE_TIME
     *
     * @return the value of user_permission_relation_delete.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission_relation_delete.CREATE_TIME
     *
     * @param createTime the value for user_permission_relation_delete.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission_relation_delete.UPDATE_TIME
     *
     * @return the value of user_permission_relation_delete.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission_relation_delete.UPDATE_TIME
     *
     * @param updateTime the value for user_permission_relation_delete.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission_relation_delete.CREATE_USER_ID
     *
     * @return the value of user_permission_relation_delete.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission_relation_delete.CREATE_USER_ID
     *
     * @param createUserId the value for user_permission_relation_delete.CREATE_USER_ID
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permission_relation_delete.UPDATE_USER_ID
     *
     * @return the value of user_permission_relation_delete.UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permission_relation_delete.UPDATE_USER_ID
     *
     * @param updateUserId the value for user_permission_relation_delete.UPDATE_USER_ID
     *
     * @mbg.generated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission_relation_delete
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", educationalStageId=").append(educationalStageId);
        sb.append(", subjectId=").append(subjectId);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", updateUserId=").append(updateUserId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}