package com.shev.itembank.task.mapper;

import com.shev.itembank.task.entity.EsBatchIndexTask;
import java.util.List;

public interface EsBatchIndexTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_batch_index_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_batch_index_task
     *
     * @mbg.generated
     */
    int insert(EsBatchIndexTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_batch_index_task
     *
     * @mbg.generated
     */
    EsBatchIndexTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_batch_index_task
     *
     * @mbg.generated
     */
    List<EsBatchIndexTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_batch_index_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EsBatchIndexTask record);
}