package com.shev.itembank.resource.mapper;

import com.shev.itembank.resource.entity.AudioAttribute;

import java.util.List;

public interface AudioAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audio_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audio_attribute
     *
     * @mbg.generated
     */
    int insert(AudioAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audio_attribute
     *
     * @mbg.generated
     */
    AudioAttribute selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audio_attribute
     *
     * @mbg.generated
     */
    List<AudioAttribute> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audio_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AudioAttribute record);
}