package com.shev.itembank.resource.mapper;

import com.shev.itembank.resource.entity.Media;
import java.util.List;

public interface MediaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbg.generated
     */
    int insert(Media record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbg.generated
     */
    Media selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbg.generated
     */
    List<Media> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Media record);
}