package com.shev.itembank.resource.mapper;

import com.shev.itembank.resource.entity.ResourcePublish;

import java.util.List;

public interface ResourcePublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_publish
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_publish
     *
     * @mbg.generated
     */
    int insert(ResourcePublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_publish
     *
     * @mbg.generated
     */
    ResourcePublish selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_publish
     *
     * @mbg.generated
     */
    List<ResourcePublish> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_publish
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResourcePublish record);
}