package com.shev.compilation.edumeta.dao.mapper;

import com.shev.compilation.edumeta.entity.ErrorMeta;

import java.util.List;

public interface ErrorMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_meta
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_meta
     *
     * @mbg.generated
     */
    int insert(ErrorMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_meta
     *
     * @mbg.generated
     */
    ErrorMeta selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_meta
     *
     * @mbg.generated
     */
    List<ErrorMeta> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_meta
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ErrorMeta record);
}