package com.shev.compilation.edumeta.dao.mapper;

import com.shev.compilation.edumeta.entity.FormType;
import java.util.List;

public interface FormTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_type
     *
     * @mbg.generated
     */
    int insert(FormType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_type
     *
     * @mbg.generated
     */
    FormType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_type
     *
     * @mbg.generated
     */
    List<FormType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FormType record);
}