package com.shev.compilation.edumeta.dao.mapper;

import com.shev.compilation.edumeta.entity.KnowledgePoint;
import java.util.List;

public interface KnowledgePointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_point
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_point
     *
     * @mbg.generated
     */
    int insert(KnowledgePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_point
     *
     * @mbg.generated
     */
    KnowledgePoint selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_point
     *
     * @mbg.generated
     */
    List<KnowledgePoint> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_point
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KnowledgePoint record);
}