package com.shev.compilation.edumeta.dao.mapper;

import com.shev.compilation.edumeta.entity.SemanticType;

import java.util.List;

public interface SemanticTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semantic_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semantic_type
     *
     * @mbg.generated
     */
    int insert(SemanticType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semantic_type
     *
     * @mbg.generated
     */
    SemanticType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semantic_type
     *
     * @mbg.generated
     */
    List<SemanticType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table semantic_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SemanticType record);
}