package com.shev.compilation.edumeta.dao.mapper;

import com.shev.compilation.edumeta.entity.Significance;

import java.util.List;

public interface SignificanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table significance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table significance
     *
     * @mbg.generated
     */
    int insert(Significance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table significance
     *
     * @mbg.generated
     */
    Significance selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table significance
     *
     * @mbg.generated
     */
    List<Significance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table significance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Significance record);
}