package com.shev.compilation.edumeta.dao.mapper;

import com.shev.compilation.edumeta.entity.Source;
import java.util.List;

public interface SourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated
     */
    int insert(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated
     */
    Source selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated
     */
    List<Source> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Source record);
}