package com.shev.compilation.edumeta.dao.mapper;

import com.shev.compilation.edumeta.entity.SourcePackage;
import java.util.List;

public interface SourcePackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_package
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_package
     *
     * @mbg.generated
     */
    int insert(SourcePackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_package
     *
     * @mbg.generated
     */
    SourcePackage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_package
     *
     * @mbg.generated
     */
    List<SourcePackage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_package
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SourcePackage record);
}