package com.shev.itembank.exercise.entity;

import java.io.Serializable;
import java.util.Date;

public class Exercise implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.FORM_TYPE
     *
     * @mbg.generated
     */
    private Integer formType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.SEMANTIC_TYPES
     *
     * @mbg.generated
     */
    private String semanticTypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.KNOWLEDGE_POINT_IDS
     *
     * @mbg.generated
     */
    private String knowledgePointIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.SOURCE_ID
     *
     * @mbg.generated
     */
    private String sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.SUBJECT_ID
     *
     * @mbg.generated
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.EDUCATIONAL_STAGE
     *
     * @mbg.generated
     */
    private Integer educationalStage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.SIGNIFICANCE
     *
     * @mbg.generated
     */
    private Integer significance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.SELECTED
     *
     * @mbg.generated
     */
    private Boolean selected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.ERROR_PRONE
     *
     * @mbg.generated
     */
    private Boolean errorProne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.RELATION_TYPE
     *
     * @mbg.generated
     */
    private String relationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.PARENT_ID
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.KP_DIFFICULTY
     *
     * @mbg.generated
     */
    private Integer kpDifficulty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.ABSOLUTE_DIFFICULTY_63
     *
     * @mbg.generated
     */
    private Integer absoluteDifficulty63;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.ABSOLUTE_DIFFICULTY_54
     *
     * @mbg.generated
     */
    private Integer absoluteDifficulty54;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.SCORE_WEIGHT
     *
     * @mbg.generated
     */
    private Long scoreWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.SEQ
     *
     * @mbg.generated
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.REF1
     *
     * @mbg.generated
     */
    private String ref1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.REF2
     *
     * @mbg.generated
     */
    private String ref2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.CREATE_YEAR
     *
     * @mbg.generated
     */
    private Integer createYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.UPDATE_YEAR
     *
     * @mbg.generated
     */
    private Integer updateYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.UPDATE_USER
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.CATEGORY_ID
     *
     * @mbg.generated
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exercise
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.ID
     *
     * @return the value of exercise.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.ID
     *
     * @param id the value for exercise.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.FORM_TYPE
     *
     * @return the value of exercise.FORM_TYPE
     *
     * @mbg.generated
     */
    public Integer getFormType() {
        return formType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.FORM_TYPE
     *
     * @param formType the value for exercise.FORM_TYPE
     *
     * @mbg.generated
     */
    public void setFormType(Integer formType) {
        this.formType = formType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.SEMANTIC_TYPES
     *
     * @return the value of exercise.SEMANTIC_TYPES
     *
     * @mbg.generated
     */
    public String getSemanticTypes() {
        return semanticTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.SEMANTIC_TYPES
     *
     * @param semanticTypes the value for exercise.SEMANTIC_TYPES
     *
     * @mbg.generated
     */
    public void setSemanticTypes(String semanticTypes) {
        this.semanticTypes = semanticTypes == null ? null : semanticTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.KNOWLEDGE_POINT_IDS
     *
     * @return the value of exercise.KNOWLEDGE_POINT_IDS
     *
     * @mbg.generated
     */
    public String getKnowledgePointIds() {
        return knowledgePointIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.KNOWLEDGE_POINT_IDS
     *
     * @param knowledgePointIds the value for exercise.KNOWLEDGE_POINT_IDS
     *
     * @mbg.generated
     */
    public void setKnowledgePointIds(String knowledgePointIds) {
        this.knowledgePointIds = knowledgePointIds == null ? null : knowledgePointIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.SOURCE_ID
     *
     * @return the value of exercise.SOURCE_ID
     *
     * @mbg.generated
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.SOURCE_ID
     *
     * @param sourceId the value for exercise.SOURCE_ID
     *
     * @mbg.generated
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.SUBJECT_ID
     *
     * @return the value of exercise.SUBJECT_ID
     *
     * @mbg.generated
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.SUBJECT_ID
     *
     * @param subjectId the value for exercise.SUBJECT_ID
     *
     * @mbg.generated
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.EDUCATIONAL_STAGE
     *
     * @return the value of exercise.EDUCATIONAL_STAGE
     *
     * @mbg.generated
     */
    public Integer getEducationalStage() {
        return educationalStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.EDUCATIONAL_STAGE
     *
     * @param educationalStage the value for exercise.EDUCATIONAL_STAGE
     *
     * @mbg.generated
     */
    public void setEducationalStage(Integer educationalStage) {
        this.educationalStage = educationalStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.SIGNIFICANCE
     *
     * @return the value of exercise.SIGNIFICANCE
     *
     * @mbg.generated
     */
    public Integer getSignificance() {
        return significance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.SIGNIFICANCE
     *
     * @param significance the value for exercise.SIGNIFICANCE
     *
     * @mbg.generated
     */
    public void setSignificance(Integer significance) {
        this.significance = significance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.SELECTED
     *
     * @return the value of exercise.SELECTED
     *
     * @mbg.generated
     */
    public Boolean getSelected() {
        return selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.SELECTED
     *
     * @param selected the value for exercise.SELECTED
     *
     * @mbg.generated
     */
    public void setSelected(Boolean selected) {
        this.selected = selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.ERROR_PRONE
     *
     * @return the value of exercise.ERROR_PRONE
     *
     * @mbg.generated
     */
    public Boolean getErrorProne() {
        return errorProne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.ERROR_PRONE
     *
     * @param errorProne the value for exercise.ERROR_PRONE
     *
     * @mbg.generated
     */
    public void setErrorProne(Boolean errorProne) {
        this.errorProne = errorProne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.CREATE_TIME
     *
     * @return the value of exercise.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.CREATE_TIME
     *
     * @param createTime the value for exercise.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.UPDATE_TIME
     *
     * @return the value of exercise.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.UPDATE_TIME
     *
     * @param updateTime the value for exercise.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.RELATION_TYPE
     *
     * @return the value of exercise.RELATION_TYPE
     *
     * @mbg.generated
     */
    public String getRelationType() {
        return relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.RELATION_TYPE
     *
     * @param relationType the value for exercise.RELATION_TYPE
     *
     * @mbg.generated
     */
    public void setRelationType(String relationType) {
        this.relationType = relationType == null ? null : relationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.PARENT_ID
     *
     * @return the value of exercise.PARENT_ID
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.PARENT_ID
     *
     * @param parentId the value for exercise.PARENT_ID
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.KP_DIFFICULTY
     *
     * @return the value of exercise.KP_DIFFICULTY
     *
     * @mbg.generated
     */
    public Integer getKpDifficulty() {
        return kpDifficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.KP_DIFFICULTY
     *
     * @param kpDifficulty the value for exercise.KP_DIFFICULTY
     *
     * @mbg.generated
     */
    public void setKpDifficulty(Integer kpDifficulty) {
        this.kpDifficulty = kpDifficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.ABSOLUTE_DIFFICULTY_63
     *
     * @return the value of exercise.ABSOLUTE_DIFFICULTY_63
     *
     * @mbg.generated
     */
    public Integer getAbsoluteDifficulty63() {
        return absoluteDifficulty63;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.ABSOLUTE_DIFFICULTY_63
     *
     * @param absoluteDifficulty63 the value for exercise.ABSOLUTE_DIFFICULTY_63
     *
     * @mbg.generated
     */
    public void setAbsoluteDifficulty63(Integer absoluteDifficulty63) {
        this.absoluteDifficulty63 = absoluteDifficulty63;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.ABSOLUTE_DIFFICULTY_54
     *
     * @return the value of exercise.ABSOLUTE_DIFFICULTY_54
     *
     * @mbg.generated
     */
    public Integer getAbsoluteDifficulty54() {
        return absoluteDifficulty54;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.ABSOLUTE_DIFFICULTY_54
     *
     * @param absoluteDifficulty54 the value for exercise.ABSOLUTE_DIFFICULTY_54
     *
     * @mbg.generated
     */
    public void setAbsoluteDifficulty54(Integer absoluteDifficulty54) {
        this.absoluteDifficulty54 = absoluteDifficulty54;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.SCORE_WEIGHT
     *
     * @return the value of exercise.SCORE_WEIGHT
     *
     * @mbg.generated
     */
    public Long getScoreWeight() {
        return scoreWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.SCORE_WEIGHT
     *
     * @param scoreWeight the value for exercise.SCORE_WEIGHT
     *
     * @mbg.generated
     */
    public void setScoreWeight(Long scoreWeight) {
        this.scoreWeight = scoreWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.SEQ
     *
     * @return the value of exercise.SEQ
     *
     * @mbg.generated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.SEQ
     *
     * @param seq the value for exercise.SEQ
     *
     * @mbg.generated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.REF1
     *
     * @return the value of exercise.REF1
     *
     * @mbg.generated
     */
    public String getRef1() {
        return ref1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.REF1
     *
     * @param ref1 the value for exercise.REF1
     *
     * @mbg.generated
     */
    public void setRef1(String ref1) {
        this.ref1 = ref1 == null ? null : ref1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.REF2
     *
     * @return the value of exercise.REF2
     *
     * @mbg.generated
     */
    public String getRef2() {
        return ref2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.REF2
     *
     * @param ref2 the value for exercise.REF2
     *
     * @mbg.generated
     */
    public void setRef2(String ref2) {
        this.ref2 = ref2 == null ? null : ref2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.CREATE_YEAR
     *
     * @return the value of exercise.CREATE_YEAR
     *
     * @mbg.generated
     */
    public Integer getCreateYear() {
        return createYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.CREATE_YEAR
     *
     * @param createYear the value for exercise.CREATE_YEAR
     *
     * @mbg.generated
     */
    public void setCreateYear(Integer createYear) {
        this.createYear = createYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.UPDATE_YEAR
     *
     * @return the value of exercise.UPDATE_YEAR
     *
     * @mbg.generated
     */
    public Integer getUpdateYear() {
        return updateYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.UPDATE_YEAR
     *
     * @param updateYear the value for exercise.UPDATE_YEAR
     *
     * @mbg.generated
     */
    public void setUpdateYear(Integer updateYear) {
        this.updateYear = updateYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.UPDATE_USER
     *
     * @return the value of exercise.UPDATE_USER
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.UPDATE_USER
     *
     * @param updateUser the value for exercise.UPDATE_USER
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.CATEGORY_ID
     *
     * @return the value of exercise.CATEGORY_ID
     *
     * @mbg.generated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.CATEGORY_ID
     *
     * @param categoryId the value for exercise.CATEGORY_ID
     *
     * @mbg.generated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.CONTENT
     *
     * @return the value of exercise.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.CONTENT
     *
     * @param content the value for exercise.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", formType=").append(formType);
        sb.append(", semanticTypes=").append(semanticTypes);
        sb.append(", knowledgePointIds=").append(knowledgePointIds);
        sb.append(", sourceId=").append(sourceId);
        sb.append(", subjectId=").append(subjectId);
        sb.append(", educationalStage=").append(educationalStage);
        sb.append(", significance=").append(significance);
        sb.append(", selected=").append(selected);
        sb.append(", errorProne=").append(errorProne);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", relationType=").append(relationType);
        sb.append(", parentId=").append(parentId);
        sb.append(", kpDifficulty=").append(kpDifficulty);
        sb.append(", absoluteDifficulty63=").append(absoluteDifficulty63);
        sb.append(", absoluteDifficulty54=").append(absoluteDifficulty54);
        sb.append(", scoreWeight=").append(scoreWeight);
        sb.append(", seq=").append(seq);
        sb.append(", ref1=").append(ref1);
        sb.append(", ref2=").append(ref2);
        sb.append(", createYear=").append(createYear);
        sb.append(", updateYear=").append(updateYear);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}